# Generated by Django 3.0.8 on 2020-08-12 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FocQues',
            fields=[
                ('ques_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_1', models.CharField(max_length=255)),
                ('a_2', models.CharField(max_length=255)),
                ('a_3', models.CharField(max_length=255)),
                ('a_4', models.CharField(max_length=255)),
                ('r_a', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'foc_ques',
            },
        ),
        migrations.CreateModel(
            name='FocTest',
            fields=[
                ('foc_id', models.AutoField(primary_key=True, serialize=False)),
                ('foc_level', models.IntegerField()),
                ('foc_voice', models.CharField(max_length=255)),
                ('foc_conv_id', models.IntegerField()),
            ],
            options={
                'db_table': 'foc_test',
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('ic_id', models.AutoField(primary_key=True, serialize=False)),
                ('ic_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'icon',
            },
        ),
        migrations.CreateModel(
            name='PhTest',
            fields=[
                ('ph_id', models.AutoField(primary_key=True, serialize=False)),
                ('ph_level', models.IntegerField()),
                ('ph_char', models.CharField(max_length=5)),
                ('ph_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ph_test',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=255)),
                ('stu_gender', models.CharField(max_length=5)),
                ('regi_date', models.DateField(auto_now_add=True)),
                ('modi_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='SwpTest',
            fields=[
                ('swp_id', models.AutoField(primary_key=True, serialize=False)),
                ('swp_level', models.IntegerField()),
                ('swp_freq', models.IntegerField()),
                ('swp_uppath', models.CharField(max_length=255)),
                ('swp_downpath', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'swp_test',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_name', models.CharField(max_length=255)),
                ('usr_email', models.CharField(max_length=255, unique=True)),
                ('usr_pw', models.CharField(max_length=255)),
                ('regi_date', models.DateField(auto_now_add=True)),
                ('modi_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UsrStu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.User')),
            ],
            options={
                'db_table': 'usr_stu',
            },
        ),
        migrations.CreateModel(
            name='StuSwp',
            fields=[
                ('ss_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_correct', models.CharField(max_length=5)),
                ('ss_date', models.DateField()),
                ('stu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
                ('swp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.SwpTest')),
            ],
            options={
                'db_table': 'stu_swp',
            },
        ),
        migrations.CreateModel(
            name='StuPh',
            fields=[
                ('sp_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_correct', models.CharField(max_length=5)),
                ('sp_date', models.DateField()),
                ('ph', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.PhTest')),
                ('stu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
            ],
            options={
                'db_table': 'stu_ph',
            },
        ),
        migrations.CreateModel(
            name='StuIc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Icon')),
                ('stu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
            ],
            options={
                'db_table': 'stu_ic',
            },
        ),
        migrations.CreateModel(
            name='StuFoc',
            fields=[
                ('sf_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_correct', models.CharField(max_length=5)),
                ('sf_date', models.DateField()),
                ('foc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.FocTest')),
                ('stu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
            ],
            options={
                'db_table': 'stu_foc',
            },
        ),
        migrations.CreateModel(
            name='ConvQues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conv_id', models.IntegerField(null=True)),
                ('ques', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.FocQues')),
            ],
            options={
                'db_table': 'conv_ques',
            },
        ),
    ]
