# Generated by Django 3.0.8 on 2020-08-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_birth',
            field=models.DateField(null=True),
        ),
    ]
