# Generated by Django 3.0.8 on 2020-08-14 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0002_student_stu_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convques',
            name='ques',
            field=models.ForeignKey(db_column='ques_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.FocQues'),
        ),
        migrations.AlterField(
            model_name='stufoc',
            name='foc',
            field=models.ForeignKey(db_column='foc_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.FocTest'),
        ),
        migrations.AlterField(
            model_name='stufoc',
            name='stu',
            field=models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student'),
        ),
        migrations.AlterField(
            model_name='stuic',
            name='ic',
            field=models.ForeignKey(db_column='ic_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Icon'),
        ),
        migrations.AlterField(
            model_name='stuic',
            name='stu',
            field=models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student'),
        ),
        migrations.AlterField(
            model_name='stuph',
            name='ph',
            field=models.ForeignKey(db_column='ph_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.PhTest'),
        ),
        migrations.AlterField(
            model_name='stuph',
            name='stu',
            field=models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student'),
        ),
        migrations.AlterField(
            model_name='stuswp',
            name='stu',
            field=models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student'),
        ),
        migrations.AlterField(
            model_name='stuswp',
            name='swp',
            field=models.ForeignKey(db_column='swp_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.SwpTest'),
        ),
        migrations.AlterField(
            model_name='usrstu',
            name='stu',
            field=models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student'),
        ),
        migrations.AlterField(
            model_name='usrstu',
            name='usr',
            field=models.ForeignKey(db_column='usr_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.User'),
        ),
    ]
