# Generated by Django 3.0.8 on 2020-08-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0004_auto_20200819_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='focques',
            name='question',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
