# Generated by Django 3.0.8 on 2020-08-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0005_focques_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuswp',
            name='ss_date',
            field=models.DateField(auto_now=True),
        ),
    ]
