# Generated by Django 3.0.8 on 2020-08-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0006_auto_20200821_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stufoc',
            name='sf_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stuph',
            name='sp_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stuswp',
            name='ss_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
