# Generated by Django 3.0.8 on 2020-08-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0007_auto_20200824_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuFocArr',
            fields=[
                ('sfarr_id', models.AutoField(primary_key=True, serialize=False)),
                ('o0', models.IntegerField()),
                ('o1', models.IntegerField()),
                ('o2', models.IntegerField()),
                ('o3', models.IntegerField()),
                ('o4', models.IntegerField()),
                ('o5', models.IntegerField()),
                ('o6', models.IntegerField()),
                ('stucnt', models.IntegerField(default=0)),
                ('stu', models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
            ],
            options={
                'db_table': 'stu_foc_arr',
            },
        ),
    ]
