# Generated by Django 3.0.8 on 2020-08-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0008_stufocarr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stufocarr',
            name='o4',
        ),
        migrations.RemoveField(
            model_name='stufocarr',
            name='o5',
        ),
        migrations.RemoveField(
            model_name='stufocarr',
            name='o6',
        ),
    ]
