# Generated by Django 3.0.8 on 2020-08-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0010_focscript'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='focscript',
            table='foc_script',
        ),
    ]
