# Generated by Django 3.0.8 on 2020-09-13 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0011_auto_20200825_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComCure',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_level', models.IntegerField()),
                ('com_w1', models.CharField(max_length=10)),
                ('com_w2', models.CharField(max_length=10)),
                ('com_w3', models.CharField(max_length=10)),
                ('com_e1', models.CharField(max_length=10)),
                ('com_e2', models.CharField(max_length=10)),
                ('com_e3', models.CharField(max_length=10)),
                ('com_e4', models.CharField(max_length=10)),
                ('com_ans', models.CharField(max_length=10)),
                ('com_w1path', models.CharField(max_length=255)),
                ('com_w2path', models.CharField(max_length=255)),
                ('com_w3path', models.CharField(max_length=255)),
                ('com_e1path', models.CharField(max_length=255)),
                ('com_e2path', models.CharField(max_length=255)),
                ('com_e3path', models.CharField(max_length=255)),
                ('com_e4path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'com_cure',
            },
        ),
        migrations.CreateModel(
            name='ConrCure',
            fields=[
                ('conr_id', models.AutoField(primary_key=True, serialize=False)),
                ('conr_level', models.IntegerField()),
                ('conr_ans', models.CharField(max_length=10)),
                ('conr_sam', models.CharField(max_length=10)),
                ('conr_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'conr_cure',
            },
        ),
        migrations.CreateModel(
            name='ConsCure',
            fields=[
                ('cons_id', models.AutoField(primary_key=True, serialize=False)),
                ('cons_word', models.CharField(max_length=10)),
                ('cons_path', models.CharField(max_length=255)),
                ('cons_e1', models.CharField(max_length=5)),
                ('cons_e2', models.CharField(max_length=5)),
                ('cons_ans', models.CharField(max_length=5)),
                ('cons_level', models.IntegerField()),
            ],
            options={
                'db_table': 'cons_cure',
            },
        ),
        migrations.CreateModel(
            name='ConwCure',
            fields=[
                ('conw_id', models.AutoField(primary_key=True, serialize=False)),
                ('conw_word', models.CharField(max_length=10)),
                ('conw_level', models.IntegerField()),
            ],
            options={
                'db_table': 'conw_cure',
            },
        ),
        migrations.CreateModel(
            name='CountCure',
            fields=[
                ('count_id', models.AutoField(primary_key=True, serialize=False)),
                ('count_word', models.CharField(max_length=10)),
                ('count_len', models.IntegerField()),
                ('count_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'count_cure',
            },
        ),
        migrations.CreateModel(
            name='MatCure',
            fields=[
                ('mat_id', models.AutoField(primary_key=True, serialize=False)),
                ('mat_word', models.CharField(max_length=10)),
                ('mat_spath', models.CharField(max_length=255)),
                ('mat_cpath', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mat_cure',
            },
        ),
        migrations.CreateModel(
            name='PoCure',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_tid', models.IntegerField()),
                ('po_text', models.CharField(max_length=255)),
                ('po_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'po_cure',
            },
        ),
        migrations.CreateModel(
            name='SelfCure',
            fields=[
                ('self_id', models.AutoField(primary_key=True, serialize=False)),
                ('self_tid', models.IntegerField()),
                ('self_text', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'self_cure',
            },
        ),
        migrations.CreateModel(
            name='TxtCure',
            fields=[
                ('txt_id', models.AutoField(primary_key=True, serialize=False)),
                ('txt_tid', models.IntegerField()),
                ('txt_text', models.CharField(max_length=255)),
                ('txt_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'txt_cure',
            },
        ),
        migrations.CreateModel(
            name='VowCure',
            fields=[
                ('vow_id', models.AutoField(primary_key=True, serialize=False)),
                ('vow_level', models.IntegerField()),
                ('vow_text', models.CharField(max_length=255)),
                ('vow_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vow_cure',
            },
        ),
        migrations.CreateModel(
            name='VowsCure',
            fields=[
                ('vows_id', models.AutoField(primary_key=True, serialize=False)),
                ('vows_level', models.IntegerField()),
                ('vows_answer', models.CharField(max_length=10)),
                ('vows_ex', models.CharField(max_length=10)),
                ('vows_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vows_cure',
            },
        ),
        migrations.CreateModel(
            name='StuVows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sv_iscorrect', models.CharField(max_length=10)),
                ('sv_date', models.DateField(auto_now_add=True)),
                ('stu', models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
                ('vows', models.ForeignKey(db_column='vows_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.VowsCure')),
            ],
            options={
                'db_table': 'stu_vows',
            },
        ),
        migrations.CreateModel(
            name='StuVow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sv_score', models.IntegerField()),
                ('sv_date', models.DateField(auto_now_add=True)),
                ('stu', models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
                ('vow', models.ForeignKey(db_column='vow_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.VowCure')),
            ],
            options={
                'db_table': 'stu_vow',
            },
        ),
        migrations.CreateModel(
            name='StuTxt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_score', models.IntegerField()),
                ('st_date', models.DateField(auto_now_add=True)),
                ('stu', models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
                ('txt', models.ForeignKey(db_column='txt_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.TxtCure')),
            ],
            options={
                'db_table': 'stu_txt',
            },
        ),
        migrations.CreateModel(
            name='StuSelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_score', models.IntegerField()),
                ('ss_date', models.DateField(auto_now_add=True)),
                ('slf', models.ForeignKey(db_column='self_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.SelfCure')),
                ('stu', models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
            ],
            options={
                'db_table': 'stu_self',
            },
        ),
        migrations.CreateModel(
            name='StuPo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_score', models.IntegerField()),
                ('sp_date', models.DateField(auto_now_add=True)),
                ('po', models.ForeignKey(db_column='po_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.PoCure')),
                ('stu', models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
            ],
            options={
                'db_table': 'stu_po',
            },
        ),
        migrations.CreateModel(
            name='StuMat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_iscorrect', models.CharField(max_length=10)),
                ('sc_sans', models.IntegerField()),
                ('sc_date', models.DateField(auto_now_add=True)),
                ('mat1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mat1', to='tt_apis.MatCure')),
                ('mat2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mat2', to='tt_apis.MatCure')),
                ('mat3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mat3', to='tt_apis.MatCure')),
                ('stu', models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
            ],
            options={
                'db_table': 'stu_mat',
            },
        ),
        migrations.CreateModel(
            name='StuCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_iscorrect', models.CharField(max_length=10)),
                ('sc_sans', models.IntegerField()),
                ('sc_date', models.DateField(auto_now_add=True)),
                ('count', models.ForeignKey(db_column='count_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.CountCure')),
                ('stu', models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
            ],
            options={
                'db_table': 'stu_count',
            },
        ),
        migrations.CreateModel(
            name='StuConw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_score', models.IntegerField()),
                ('sc_date', models.DateField(auto_now_add=True)),
                ('conw', models.ForeignKey(db_column='conw_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.ConwCure')),
                ('stu', models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
            ],
            options={
                'db_table': 'stu_conw',
            },
        ),
        migrations.CreateModel(
            name='StuCons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_iscorrect', models.CharField(max_length=10)),
                ('sc_date', models.DateField(auto_now_add=True)),
                ('cons', models.ForeignKey(db_column='cons_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.ConsCure')),
                ('stu', models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
            ],
            options={
                'db_table': 'stu_cons',
            },
        ),
        migrations.CreateModel(
            name='StuConr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_iscorrect', models.IntegerField()),
                ('sc_date', models.DateField(auto_now_add=True)),
                ('conr', models.ForeignKey(db_column='conr_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.ConrCure')),
                ('stu', models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
            ],
            options={
                'db_table': 'stu_conr',
            },
        ),
        migrations.CreateModel(
            name='StuCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_iscorrect', models.CharField(max_length=10)),
                ('sc_sans', models.IntegerField()),
                ('sc_date', models.DateField(auto_now_add=True)),
                ('com', models.ForeignKey(db_column='com_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.ComCure')),
                ('stu', models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
            ],
            options={
                'db_table': 'stu_com',
            },
        ),
    ]
