# Generated by Django 3.0.8 on 2020-09-18 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0012_comcure_conrcure_conscure_conwcure_countcure_matcure_pocure_selfcure_stucom_stuconr_stucons_stuconw_'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestIdx',
            fields=[
                ('idx_id', models.AutoField(primary_key=True, serialize=False)),
                ('idx_txt', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'text_idx',
            },
        ),
        migrations.CreateModel(
            name='TestMaster',
            fields=[
                ('ques_id', models.AutoField(primary_key=True, serialize=False)),
                ('ques_level', models.IntegerField()),
                ('ques_path1', models.CharField(max_length=255)),
                ('ques_path2', models.CharField(max_length=255, null=True)),
                ('ques_int', models.IntegerField(null=True)),
                ('ques_char', models.CharField(max_length=10, null=True)),
                ('test_idx', models.ForeignKey(db_column='idx_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.TestIdx')),
            ],
            options={
                'db_table': 'test_master',
            },
        ),
        migrations.RemoveField(
            model_name='convques',
            name='ques',
        ),
        migrations.RemoveField(
            model_name='stucom',
            name='com',
        ),
        migrations.RemoveField(
            model_name='stucom',
            name='stu',
        ),
        migrations.RemoveField(
            model_name='stuconr',
            name='conr',
        ),
        migrations.RemoveField(
            model_name='stuconr',
            name='stu',
        ),
        migrations.RemoveField(
            model_name='stucons',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='stucons',
            name='stu',
        ),
        migrations.RemoveField(
            model_name='stuconw',
            name='conw',
        ),
        migrations.RemoveField(
            model_name='stuconw',
            name='stu',
        ),
        migrations.RemoveField(
            model_name='stucount',
            name='count',
        ),
        migrations.RemoveField(
            model_name='stucount',
            name='stu',
        ),
        migrations.RemoveField(
            model_name='stumat',
            name='mat1',
        ),
        migrations.RemoveField(
            model_name='stumat',
            name='mat2',
        ),
        migrations.RemoveField(
            model_name='stumat',
            name='mat3',
        ),
        migrations.RemoveField(
            model_name='stumat',
            name='stu',
        ),
        migrations.RemoveField(
            model_name='stupo',
            name='po',
        ),
        migrations.RemoveField(
            model_name='stupo',
            name='stu',
        ),
        migrations.RemoveField(
            model_name='stuself',
            name='slf',
        ),
        migrations.RemoveField(
            model_name='stuself',
            name='stu',
        ),
        migrations.RemoveField(
            model_name='stutxt',
            name='stu',
        ),
        migrations.RemoveField(
            model_name='stutxt',
            name='txt',
        ),
        migrations.RemoveField(
            model_name='stuvow',
            name='stu',
        ),
        migrations.RemoveField(
            model_name='stuvow',
            name='vow',
        ),
        migrations.RemoveField(
            model_name='stuvows',
            name='stu',
        ),
        migrations.RemoveField(
            model_name='stuvows',
            name='vows',
        ),
        migrations.RemoveField(
            model_name='foctest',
            name='foc_conv_id',
        ),
        migrations.DeleteModel(
            name='ComCure',
        ),
        migrations.DeleteModel(
            name='ConrCure',
        ),
        migrations.DeleteModel(
            name='ConsCure',
        ),
        migrations.DeleteModel(
            name='ConvQues',
        ),
        migrations.DeleteModel(
            name='ConwCure',
        ),
        migrations.DeleteModel(
            name='CountCure',
        ),
        migrations.DeleteModel(
            name='FocQues',
        ),
        migrations.DeleteModel(
            name='MatCure',
        ),
        migrations.DeleteModel(
            name='PoCure',
        ),
        migrations.DeleteModel(
            name='SelfCure',
        ),
        migrations.DeleteModel(
            name='StuCom',
        ),
        migrations.DeleteModel(
            name='StuConr',
        ),
        migrations.DeleteModel(
            name='StuCons',
        ),
        migrations.DeleteModel(
            name='StuConw',
        ),
        migrations.DeleteModel(
            name='StuCount',
        ),
        migrations.DeleteModel(
            name='StuMat',
        ),
        migrations.DeleteModel(
            name='StuPo',
        ),
        migrations.DeleteModel(
            name='StuSelf',
        ),
        migrations.DeleteModel(
            name='StuTxt',
        ),
        migrations.DeleteModel(
            name='StuVow',
        ),
        migrations.DeleteModel(
            name='StuVows',
        ),
        migrations.DeleteModel(
            name='TxtCure',
        ),
        migrations.DeleteModel(
            name='VowCure',
        ),
        migrations.DeleteModel(
            name='VowsCure',
        ),
        migrations.AddField(
            model_name='stutest',
            name='ques',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ques_normal', to='tt_apis.TestMaster'),
        ),
        migrations.AddField(
            model_name='stutest',
            name='ques2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ques_ph', to='tt_apis.TestMaster'),
        ),
        migrations.AddField(
            model_name='stutest',
            name='stu',
            field=models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student'),
        ),
    ]
