# Generated by Django 3.0.8 on 2020-09-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0013_auto_20200918_1614'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stutest',
            table='stu_test',
        ),
    ]
