# Generated by Django 3.0.8 on 2020-09-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0014_auto_20200918_1615'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testidx',
            table='test_idx',
        ),
    ]
