# Generated by Django 3.0.8 on 2020-09-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0015_auto_20200918_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='stutest',
            name='test_txt',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
