# Generated by Django 3.0.8 on 2020-09-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0016_stutest_test_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stufoc',
            name='foc',
        ),
        migrations.RemoveField(
            model_name='stufoc',
            name='stu',
        ),
        migrations.RemoveField(
            model_name='stuph',
            name='ph1',
        ),
        migrations.RemoveField(
            model_name='stuph',
            name='ph2',
        ),
        migrations.RemoveField(
            model_name='stuph',
            name='stu',
        ),
        migrations.RemoveField(
            model_name='stuswp',
            name='stu',
        ),
        migrations.RemoveField(
            model_name='stuswp',
            name='swp',
        ),
        migrations.DeleteModel(
            name='FocTest',
        ),
        migrations.DeleteModel(
            name='PhTest',
        ),
        migrations.DeleteModel(
            name='StuFoc',
        ),
        migrations.DeleteModel(
            name='StuPh',
        ),
        migrations.DeleteModel(
            name='StuSwp',
        ),
        migrations.DeleteModel(
            name='SwpTest',
        ),
    ]
