# Generated by Django 3.0.8 on 2020-09-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0017_auto_20200918_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComCure',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_level', models.IntegerField()),
                ('com_w1', models.CharField(max_length=10)),
                ('com_w2', models.CharField(max_length=10)),
                ('com_w3', models.CharField(max_length=10)),
                ('com_e1', models.CharField(max_length=10)),
                ('com_e2', models.CharField(max_length=10)),
                ('com_e3', models.CharField(max_length=10)),
                ('com_e4', models.CharField(max_length=10)),
                ('com_ans', models.CharField(max_length=10)),
                ('com_w1path', models.CharField(max_length=255)),
                ('com_w2path', models.CharField(max_length=255)),
                ('com_w3path', models.CharField(max_length=255)),
                ('com_e1path', models.CharField(max_length=255)),
                ('com_e2path', models.CharField(max_length=255)),
                ('com_e3path', models.CharField(max_length=255)),
                ('com_e4path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'com_cure',
            },
        ),
        migrations.CreateModel(
            name='CureIdx',
            fields=[
                ('idx_id', models.AutoField(primary_key=True, serialize=False)),
                ('idx_txt', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'cure_idx',
            },
        ),
        migrations.CreateModel(
            name='CureMaster',
            fields=[
                ('cure_id', models.AutoField(primary_key=True, serialize=False)),
                ('cure_level', models.IntegerField(null=True)),
                ('cure_path', models.CharField(max_length=255)),
                ('cure_path2', models.CharField(max_length=255)),
                ('cure_tid', models.IntegerField(null=True)),
                ('cure_word', models.CharField(max_length=10)),
                ('cure_word2', models.CharField(max_length=10)),
                ('cure_text', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cure_master',
            },
        ),
    ]
