# Generated by Django 3.0.8 on 2020-09-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0018_comcure_cureidx_curemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cureidx',
            name='idx_txt',
            field=models.CharField(max_length=20),
        ),
    ]
