# Generated by Django 3.0.8 on 2020-09-20 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0019_auto_20200920_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainImg',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_path', models.CharField(max_length=255)),
                ('img_desc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'main_img',
            },
        ),
        migrations.CreateModel(
            name='WordImg',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_path', models.CharField(max_length=255)),
                ('img_desc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'word_img',
            },
        ),
        migrations.CreateModel(
            name='StuCure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cure_txt', models.CharField(max_length=10, null=True)),
                ('is_correct', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1)),
                ('cure_rate', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('cure', models.ForeignKey(db_column='cure_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.CureMaster')),
                ('cure2', models.ForeignKey(db_column='com_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.ComCure')),
                ('stu', models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
            ],
            options={
                'db_table': 'stu_cure',
            },
        ),
    ]
