# Generated by Django 3.0.8 on 2020-09-21 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0020_mainimg_stucure_wordimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='curemaster',
            name='cure_idx',
            field=models.ForeignKey(db_column='idx_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.CureIdx'),
        ),
    ]
