# Generated by Django 3.0.8 on 2020-10-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0021_curemaster_cure_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stucure',
            old_name='cure_rate',
            new_name='full_score',
        ),
        migrations.AddField(
            model_name='stucure',
            name='phone_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stucure',
            name='rhythm_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stucure',
            name='speed_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stutest',
            name='full_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stutest',
            name='phone_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stutest',
            name='rhythm_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stutest',
            name='speed_score',
            field=models.IntegerField(null=True),
        ),
    ]
