# Generated by Django 3.0.8 on 2020-10-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0022_auto_20201004_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stucure',
            name='cure_txt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
