# Generated by Django 3.0.8 on 2020-10-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0023_auto_20201005_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='cureidx',
            name='curr_ordere',
            field=models.IntegerField(null=True),
        ),
    ]
