# Generated by Django 3.0.8 on 2020-10-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0024_cureidx_curr_ordere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cureidx',
            old_name='curr_ordere',
            new_name='curr_order',
        ),
    ]
