# Generated by Django 3.0.8 on 2020-10-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0025_auto_20201007_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='cureidx',
            name='read_order',
            field=models.IntegerField(null=True),
        ),
    ]
