# Generated by Django 3.0.8 on 2020-10-07 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0026_cureidx_read_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuCurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_read', models.CharField(max_length=50)),
                ('cur_curr', models.CharField(max_length=50)),
                ('cur_read_pid', models.IntegerField(null=True)),
                ('cur_curr_last1', models.IntegerField(null=True)),
                ('cur_curr_last2', models.IntegerField(null=True)),
                ('cur_curr_last3', models.IntegerField(null=True)),
                ('stu', models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
            ],
            options={
                'db_table': 'stu_current',
            },
        ),
    ]
