# Generated by Django 3.0.8 on 2020-10-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0027_stucurrent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stucurrent',
            old_name='cur_read_pid',
            new_name='cur_read_id',
        ),
    ]
