# Generated by Django 3.0.8 on 2020-10-07 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0029_auto_20201007_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stucure',
            old_name='cure2',
            new_name='com_cure',
        ),
        migrations.AddField(
            model_name='stucure',
            name='cure_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='q2', to='tt_apis.CureMaster'),
        ),
        migrations.AddField(
            model_name='stucure',
            name='cure_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='q3', to='tt_apis.CureMaster'),
        ),
        migrations.AlterField(
            model_name='stucure',
            name='cure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='q1', to='tt_apis.CureMaster'),
        ),
    ]
