# Generated by Django 3.0.8 on 2020-10-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0030_auto_20201008_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='stucure',
            name='is_review',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1, null=True),
        ),
    ]
