# Generated by Django 3.0.8 on 2020-10-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0031_stucure_is_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stucure',
            name='is_correct',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1, null=True),
        ),
    ]
