# Generated by Django 3.0.8 on 2020-10-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0032_auto_20201009_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='stucure',
            name='ori_answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stucure',
            name='stu_answer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
