# Generated by Django 3.0.8 on 2020-10-12 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0033_auto_20201010_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swp_freq', models.IntegerField(null=True)),
                ('swp_len', models.IntegerField(null=True)),
                ('focus_lev', models.IntegerField(null=True)),
                ('stu', models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
            ],
            options={
                'db_table': 'test_current',
            },
        ),
    ]
