# Generated by Django 3.0.8 on 2020-10-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0034_testcurrent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcurrent',
            old_name='swp_len',
            new_name='swp_lev',
        ),
    ]
