# Generated by Django 3.0.8 on 2020-10-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0035_auto_20201012_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcurrent',
            name='swp_passed',
            field=models.IntegerField(null=True),
        ),
    ]
