# Generated by Django 3.0.8 on 2020-10-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0038_testcurrent_swp_did'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcurrent',
            name='focus_passed',
            field=models.IntegerField(null=True),
        ),
    ]
