# Generated by Django 3.0.8 on 2020-10-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0039_testcurrent_focus_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcurrent',
            name='focus_did',
            field=models.IntegerField(null=True),
        ),
    ]
