# Generated by Django 3.0.8 on 2020-10-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0040_testcurrent_focus_did'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('voc_id', models.AutoField(primary_key=True, serialize=False)),
                ('voc_path', models.CharField(max_length=255)),
                ('voc_desc', models.CharField(max_length=255)),
                ('voc_script', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'voice',
            },
        ),
    ]
