# Generated by Django 3.0.8 on 2020-10-27 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0041_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ic',
            field=models.ForeignKey(db_column='ic_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Icon'),
        ),
    ]
