# Generated by Django 3.0.8 on 2020-10-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0043_auto_20201028_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='stucure',
            name='is_daily',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1, null=True),
        ),
    ]
