# Generated by Django 3.0.8 on 2020-11-02 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0044_stucure_is_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('stu', models.ForeignKey(db_column='stu_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tt_apis.Student')),
            ],
            options={
                'db_table': 'stu_status',
            },
        ),
    ]
