# Generated by Django 3.0.8 on 2020-11-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0045_stustatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stustatus',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
