# Generated by Django 3.0.8 on 2020-11-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0046_auto_20201102_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='stucure',
            name='is_first',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1, null=True),
        ),
    ]
