# Generated by Django 3.0.8 on 2020-11-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_apis', '0047_stucure_is_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_birth',
            field=models.IntegerField(null=True),
        ),
    ]
